max_width = 120
fn_params_layout = "Vertical"
merge_imports = true
group_imports = "StdExternalCrate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 20
struct_variant_width = 0
use_field_init_shorthand = true
wrap_comments = true